name: HouseControl
version: 0.01
author: Victor Martinez
main: es.victor.mcplugins.HouseControl.MainHouseControl
api-version: 1.13
commands:
  house:
    description: Interact with the house plugin
    usage: /house